export const ALERT = {
    SUCCESS: "ALERT_SUCCESS",
    INFO: "ALERT_INFO",
    ERROR: "ALERT_ERROR",
    CLEAR: "ALERT_CLEAR",
};

export const USER = {
    SET_DATE: 'USER_SET_DATA',
    UNSET_DATA: 'UNSET_USER_DATA',
    GET_DATA: 'GET_USER_DATA',
    REDIRECT: 'USER_REDIRECT'
};

export const NAVIGATION = {
    RELOAD: "NAV_RELOAD",
    CLEAR: "NAV_CLEAR",
};

export const SELECT = {
    GET_DATA: 'SELECT_GET_DATA',
    SET_DATA: 'SELECT_SET_DATA',
    UNSET_DATA: 'SELECT_UNSET_DATA',

    GET_LOADING: 'SELECT_GET_LOADING',
    SET_LOADING: 'SELECT_SET_LOADING',
    UNSET_LOADING: 'SELECT_UNSET_LOADING',
};


